### ISSUE TITLE
Slinks not working properly other than normal layout when draw lines from subtrees

### ISSUE THREAD

**Issue by ahwar123** [BALKANGraph/OrgChartJS#838]
I've encountered an issue with the functionality of Chart Slinks in the latest version. The problem arises when attempting to utilize Chart Slinks, as they are not working as expected. Specifically, when we draw line from subtree to parent node. this lines are not draw correctly.
This issue is coming on all the layouts except normal layout.

image is for your reference

![image](https://github.com/BALKANGraph/OrgChartJS/assets/25219928/a0dd5029-3948-4c90-9707-9a6f82d420d2)

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in a code example:
https://code.balkan.app/org-chart-js/simple-example#JS

**Comment by ahwar123** [comment]
Kindly find sample code below.
https://code.balkan.app/slinkdemo#JS

**Comment by ZornitsaPesheva** [comment]
Thank you. We will try to fix it soon.

**Comment by ZornitsaPesheva** [comment]
The issue is fixed. Please get the latest verion.

**Comment by ahwar123** [comment]
Thanks @ZornitsaPesheva for the quick update. Its fixed now.

**Comment by ahwar123** [comment]
Hi @ZornitsaPesheva, Hope you are fine.

I am encountering an issue with the organizational chart. The chart operates flawlessly in the local environment, but it encounters an issue when deployed to the production environment. Specifically, the issue arises when handling a larger set of nodes (approximately more than 80 nodes). While the chart functions correctly with a smaller set of nodes, it gets stuck when dealing with a larger dataset.

Additionally, it appears that an API call in the production environment is being affected and becomes unresponsive under these conditions.

I have attached relevant screenshots for your reference to help illustrate the problem. Could you please provide guidance or suggest any troubleshooting steps to resolve this issue?

Thank you for your assistance.


![Screenshot_3](https://github.com/BALKANGraph/OrgChartJS/assets/25219928/ba4c0dd3-cd7d-44dc-9e03-4016bd992107)

![Screenshot_4](https://github.com/BALKANGraph/OrgChartJS/assets/25219928/bb524389-66bf-4724-9174-8b3de022b5e0)

**Comment by ZornitsaPesheva** [comment]
Please try to clear the browser cache (Ctrl+F5) and let me know if this fixes the issue.

**Comment by ahwar123** [comment]
Yes, i already performed Hard refresh and clear cache of the browser page but still the same issue. The API request remains stuck in a pending state.

**Comment by ZornitsaPesheva** [comment]
Please give me the result of this:
console.log(OrgChart.VERSION)

**Comment by ahwar123** [comment]
8.14.40
